### ISSUE TITLE
getting HTTP Error 403: Forbidden for a valid server/browser key

### ISSUE THREAD

**Issue by adolg** [afilipovich/gglsbl#12]
I know this error:
`  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
`
popped up a couple of times, but that was due to old format of API keys.
I'm using the current one, from Developer Console, created as described here:
https://developers.google.com/safe-browsing/v3/update-guide#GettingStarted

and I'm trying to execute
`gglsbl_client.py --api-key ... --onetime`
but keep getting 403 forbidden (tried both Server and Browser key). Can someone enlighten me on this... TIA!

**Comment by afilipovich** [comment]
Which API is the key associated with?
I guess it should be "Safe Browsing API (Legacy)".

**Comment by adolg** [comment]
Yes, I didn't realize that just "Safe Browsing API" would apply only to v4.
Maybe worth noting in the readme.md?

**Comment by afilipovich** [comment]
Yeah, that makes sense given that v4 is out.
I assume the issue is resolved.
