### ISSUE TITLE
URLs with Unicode cause exception

### ISSUE THREAD

**Issue by asieira** [afilipovich/gglsbl#17]
I am getting an exception when the URLs have Unicode characters in them:
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gglsbl import SafeBrowsingList
>>> sbl = SafeBrowsingList('<redacted>')
>>> sbl.lookup_url(u"http://www.google.com/?q=áéíóú'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gglsbl/client.py", line 111, in lookup_url
    url_hashes = URL(url).hashes
  File "/usr/local/lib/python2.7/site-packages/gglsbl/protocol.py", line 158, in __init__
    self.url = str(url)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 25-29: ordinal not in range(128)
```

I'm not sure what is the best way to handle this, either make the protocol handler be Unicode-aware, or perhaps percent-encode any non-ASCII characters.

**Comment by afilipovich** [comment]
Thanks for the code snippet and stack trace.
I have pushed a fix to "master" branch, can you please check if it works for you?

**Comment by asieira** [comment]
Yes, it works now. Thanks for the quick turnaround time. :+1: 🙇

**Comment by asieira** [comment]
Would really appreciate it if you could push a new release with the last few fixes and improvements to PyPI. 🙇

**Comment by Stefan-Code** [comment]
@afilipovich 
A bit OT, but would you be interested in merging the Unit Tests and build pipeline from the now outdated gglsbl3 fork into here?
E.g.  automated deployment from Travis to PyPI.

**Comment by afilipovich** [comment]
@Stefan-Code: yes, definitely. Will you have time to help with it?

**Comment by afilipovich** [comment]
@asieira: tagged and pushed new release.

**Comment by Stefan-Code** [comment]
@afilipovich I should be able to find some time for that. Just send me an email (see my profile).
