### ISSUE TITLE
Question: is it possible to download all full digests?

### ISSUE THREAD

**Issue by monperrus** [afilipovich/gglsbl#23]
With gglsbl, is it possible to download all full digests by querying the completer for all short 4-bytes hashes?

Would the Google API throttling be the only problem?

**Comment by afilipovich** [comment]
In theory it should be possible with some code changes. However there are about 10MM active hash prefixes while maximum API queries quota is 10K per day...

Curious how would you use such set of all full digests?

**Comment by monperrus** [comment]
> However there are about 10MM active hash prefixes while maximum API queries quota is 10K per day...
This is not a direct division because one can ask for several completions at the same time (param
threatEntries).

Do you know the maximum number of threatEntries? (doesn't seem documented in
https://developers.google.com/safe-browsing/v4/update-api)

**Comment by afilipovich** [comment]
True that, however I do not know the maximum number of entries per call.

**Comment by monperrus** [comment]
Super interesting page: https://www.google.com/transparencyreport/safebrowsing/

approx 20000 new phishing sites per week added in Safe Browsing, a little less malware sites.

**Comment by monperrus** [comment]
maximum number of prefix entries per call: 1000 entries in Safe Browsing v3 (limit found with testing)

**Comment by afilipovich** [comment]
Thanks, it's good to know that.
