### ISSUE TITLE
This package not work with windows.

### ISSUE THREAD

**Issue by nkh8212** [afilipovich/gglsbl#26]
client.py :21 line
 ``` 
def __init__(self, api_key, db_path='/tmp/gsb_v4.db', discard_fair_use_policy=False, 
```

This will cause sqlite error, because windows does not have path('/tmp/gsb_v4.db').

I just changed path to './gsb_v4.db' and It work fine.

**Comment by afilipovich** [comment]
Ok, thanks for the notice.

I think it's better to keep current default setting as changing it may break existing installations which rely on that default, while on platforms that do not have `/tmp` directory it can be solved by passing `db_path` parameter to constructor.
