### ISSUE TITLE
Set sqlite database to WAL mode

### ISSUE THREAD

**Issue by asieira** [afilipovich/gglsbl#29]
As briefly discussed on https://github.com/afilipovich/gglsbl/issues/28 I think it would be a good idea to set the sqlite database to [WAL mode](https://sqlite.org/wal.html). This would allow the update process to happen concurrently with queries, and that would bode well for multiprocess use of gglsbl, such as what we do in [gglsbl-rest](https://github.com/mlsecproject/gglsbl-rest).

That would involve:
* Removing the current `PRAGMA synchronous = 0` entry;
* Issuing a `PRAGMA journal_mode=WAL` when the database is created;
* Perhaps exposing a method on the client class that allows a [WAL checkpoint](https://sqlite.org/pragma.html#pragma_wal_checkpoint) to be performed. In gglsbl-rest, for example, there is a regular chron job that could execute the PASSIVE checkpoint at regular intervals.

If this was implemented, I think [gglsbl-rest](https://github.com/mlsecproject/gglsbl-rest) could do away with maintaining two separate databases and instead work with a single one. That would simplify things tremendously, reduce disk space usage and possibly eliminate race conditions in the database-switching logic.

**Comment by afilipovich** [comment]
I like the idea of having a single DB file, it will preserve already downloaded data between cache updates and will preserve cached full hash entries.

I will add a parameter to run either in WAL or async mode. Originally I added `PRAGMA synchronous = 0` to prevent every single operation being flushed to disk, this gives 3-10x speedup (I use this library to check large batches of ~10MM URLs), but makes cache DB more fragile.

**Comment by asieira** [comment]
Perhaps setting `PRAGMA synchronous = NORMAL` could be a good compromise, and [the documentation](https://sqlite.org/pragma.html#pragma_synchronous) explicitly mentions this is what is most often used with WAL.

**Comment by afilipovich** [comment]
I did performance tests, WAL mode is ~10% slower than default one, but it is well worth it given that it allows concurrent writes. I keep `PRAGMA synchronous = 0` as we do not care about durability here (if server loses power, Docker will be destroyed anyway).

I have pushed the change to `master` branch but haven't tagged release yet. Would be able to test this change under real load with lookups and update using same DB?

**Comment by asieira** [comment]
10% sounds a bit high. Still worth it, but more than what I expected.

Did you try issuing a check point right after the update? I'm assuming that doing that and thus incorporating the write-ahead log back into the main database should reduce the performance impact.

**Comment by afilipovich** [comment]
I am pretty sure Sqlite does multiple checkpoints during update and a final one after transaction is committed given that DB file is 2G.

If you need as much performance as you can get, try storing .sqlite file on RAMdisk, e.g. in `/dev/shm`, or `/tmp` dir mounted on `tmpfs`. You will at least double performance compared to SSD. However your server should have at least 4G of RAM to fit the data and all the moving parts.

**Comment by asieira** [comment]
I just realized I could do the WAL mode and the different synchronous mode directly by accessing `sbl.storage.db`. Will try that now.

**Comment by asieira** [comment]
I'm going to try running this for a while and see how it performs: https://github.com/mlsecproject/gglsbl-rest/commit/8c41760061e7efff2cbb4de06093e4a19dfcce79

**Comment by asieira** [comment]
Since I can do everything on gglsbl-rest code by accessing the storage object directly, I recommend you remove that commit you did to `master` and I'll close this now. Thank you for your help and ideas, as usual. 🙇

**Comment by afilipovich** [comment]
Ok, thanks, please let me know how it goes. If WAL mode works well with concurrent lookup/update I might leave this commit for improved robustness.

**Comment by asieira** [comment]
Confirmed that it did work well in production, and merged changes into v1.4.0 of gglsbl-rest.

**Comment by asieira** [comment]
Not only did I not see any negative impact, no longer switching databases has improved performance quite a bit.

**Comment by afilipovich** [comment]
Nice!
