### ISSUE TITLE
Site not detected

### ISSUE THREAD

**Issue by zwayne** [afilipovich/gglsbl#31]
The site http://0-facebook.com/q reports as unsafe on the transparency report, but isn't blacklisted when I run gglsbl. I initialized a new DB just now & it still says safe. 

Do you have a good explanation for this difference?

**Comment by zwayne** [comment]
I used the Java API provided by Google and got the same result as gglsbl, i.e., not blacklisted. 

My guess is the transparency report https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2F0-facebook.com%2Fq is either out of date OR uses additional resources not provided to us. 

I will close this issue. Thanks for writing this implementation in python. We are using it with the rest frontend and find both very useful.

**Comment by afilipovich** [comment]
Thanks @zwayne, happy to know that!
