### ISSUE TITLE
Error in storage.py:cleanup_full_hashes()

### ISSUE THREAD

**Issue by artgl** [afilipovich/gglsbl#32]
It seems that query to clean up full_hash entries expired more than X seconds ago is incorrect. It should be:
`DELETE FROM full_hash WHERE expires_at < datetime(current_timestamp, '-{} SECONDS')`
instead of (in current code)
`DELETE FROM full_hash WHERE expires_at=datetime(current_timestamp, '{} SECONDS')`

**Comment by afilipovich** [comment]
Thanks @artgl, there is a bug indeed.
I've applied your fix to v1.4.7.
