### ISSUE TITLE
GSB not returning correct results

### ISSUE THREAD

**Issue by pappumaster** [afilipovich/gglsbl#34]
Hello,

(I realize this is probably not the right place to ask this question, but I can't delete this issue anymore, so hopefully, someone will be able to answer me).

I've followed the instructions to install this python library which then sets up a 1.7G database. Whenever I try any URL even those which are supposed to be blacklisted like ianfette, it keeps saying that it is a clean URL. Am I missing a step here?

Thank you!

**Comment by afilipovich** [comment]
Hi @pappumaster, can you please provide several URLs which you expect to be blacklisted?

**Comment by pappumaster** [comment]
Sure, these are 3 that I am expecting to see:

1) right-beauty.com
2) my-mobil-device.club
3) http://ianfette.org

**Comment by afilipovich** [comment]
Just checked my setup, URLs 1 and 2 are reported as blacklisted. URL 3 is reported as clean.

URL 3 is reported as clean by Google Safe Browsing Status page:
https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fianfette.org%2F

Could you please check again? Also, what version of `gglsbl` library do you use?

**Comment by pappumaster** [comment]
I am using the latest version of the repo (updated Feb 27th). I just ran update_hash_prefix_cache() again. And I am running the lookup against the first two URLs and now it is taking several minutes to complete. It is still not completed after 10 minutes, i.e., I have yet to see the lookup complete and return a blacklisted result.

**Comment by afilipovich** [comment]
Can you please paste the log?

**Comment by pappumaster** [comment]
Hi, I am not sure what changed, but when I just went to try it again and paste the logs, I am now getting results and it seems to be working. So I guess this is resolved now. Thank you!

**Comment by afilipovich** [comment]
Ok, thanks for confirmation. It appears like a transient issue with network connection to Google API.

**Comment by afilipovich** [comment]
It double-checks with Google URLs that match local DB. Here are details if you are interested:
https://developers.google.com/safe-browsing/v4/update-api
