### ISSUE TITLE
How to remove the process of verify in Google server?

### ISSUE THREAD

**Issue by wtbsw** [afilipovich/gglsbl#39]
Dear sir:
    There is a problem for me, getting VPN for me to use google smoothly is too difficult, so how can i remove the process of verifying  in google server when a url is in the local database blacklist?
    Thank you very much for help.

**Comment by afilipovich** [comment]
Unfortunately it is not possible to avoid full hash lookup - local database stores first 4 bytes of hash prefix and there is a high chance for random clean URL to match local cache.

**Comment by wtbsw** [comment]
Thank you for help. I will try proxy.
