### ISSUE TITLE
Place link to Python 3 version in README

### ISSUE THREAD

**Issue by Stefan-Code** [afilipovich/gglsbl#4]
Hi, 
I created a Python 3 (only) version of this library that can be found [here](https://github.com/Stefan-Code/gglsbl3) (And also changed a bunch of other things, like unit tests and metadata for a lookup). A small hint in the README would be useful for people who want to use the library with python 3.

Best Regards,
Stefan

**Comment by afilipovich** [comment]
Hi Stefan,
thank you for making Python3 port available, I have added a link to your project to README.

Kind regards,
Aleh

**Comment by Stefan-Code** [comment]
Hi Aleh,
thanks for putting the link in the README.
And also a big thank you for creating such an awesome library i could port! :smiley: 

Best Regards,
Stefan
