### ISSUE TITLE
SafeBrowsingListTestCase FAIL

### ISSUE THREAD

**Issue by pczzy** [afilipovich/gglsbl#42]
python -m unittest -v tests.py 
test_canonicalize (tests.SafeBrowsingListTestCase) ... FAIL
test_permutations (tests.SafeBrowsingListTestCase) ... ok

======================================================================
FAIL: test_canonicalize (tests.SafeBrowsingListTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/super/anaconda3/lib/python3.7/site-packages/gglsbl/tests.py", line 109, in test_canonicalize
    self.assertEqual(URL(nu).canonical, cu)
AssertionError: "http://b'http/\\x01\\x80.com/'" != 'http://%01%80.com/'
- http://b'http/\x01\x80.com/'
+ http://%01%80.com/

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (failures=1)

**Comment by afilipovich** [comment]
Thanks for reporting, looks like python3.7 works slightly differently with byte strings.

**Comment by afilipovich** [comment]
Pushed the fix to "master" branch.

**Comment by afilipovich** [comment]
Fixed in release v1.4.14.

**Comment by Fujiaoji** [comment]
When I make a copy of the SafeBrowsingListTestCase, I find that this sample get something wrong. Could you please tell me the reason? Thank you. I run it on python3.10.6.
FAIL: test_canonicalize (__main__.SafeBrowsingListTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "XXXX/test.py", line 177, in test_canonicalize
    self.assertEqual(URL(nu).canonical, cu)
AssertionError: 'http://3279880203/blah' != 'http://195.127.0.11/blah'
- http://3279880203/blah
+ http://195.127.0.11/blah
----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
