### ISSUE TITLE
minimumWaitDuration should be separated for for get_threats_update and get_full_hashes

### ISSUE THREAD

**Issue by wiebren** [afilipovich/gglsbl#50]
There is currently a single wait period for all calls, however the docs mention the `minimumWaitDuration` is separate per call type:

https://developers.google.com/safe-browsing/v4/reference/rest/v4/threatListUpdates/fetch
> The minimum duration the client must wait **before issuing any update request**. If this field is not set clients may update as soon as they want.

https://developers.google.com/safe-browsing/v4/reference/rest/v4/fullHashes/find
> The minimum duration the client must wait **before issuing any find hashes request**. If this field is not set, clients can issue a request as soon as they want.

Also `get_threats_lists` has handling for `minimumWaitDuration`, but the docs do not mention this response field in the `threatLists.list` call 

https://developers.google.com/safe-browsing/v4/reference/rest/v4/threatLists/list

**Comment by afilipovich** [comment]
Thanks @YoitoFes
