### ISSUE TITLE
SafeBrowsingListTestCase Wrong

### ISSUE THREAD

**Issue by Fujiaoji** [afilipovich/gglsbl#52]
When I make a copy of the SafeBrowsingListTestCase, I find that this sample get something wrong. Could you please tell me the reason? Thank you. I run it on python3.10.6.
F
======================================================================
FAIL: test_canonicalize (__main__.SafeBrowsingListTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fujiao/Workspace/code/test.py", line 177, in test_canonicalize
    self.assertEqual(URL(nu).canonical, cu)
AssertionError: 'http://3279880203/blah' != 'http://195.127.0.11/blah'
- http://3279880203/blah
+ http://195.127.0.11/blah

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)

**Comment by Fujiaoji** [comment]
Also, could you please tell me how to only use the local blacklist rather than using the google api? Since I already download the blacklist and would like to set the blacklist dataset. Thanks

**Comment by afilipovich** [comment]
Hi, I was not able to replicate this issue, perhaps it depends on OS or architecture. What system are you running it at?

As for the second question, all blacklist entries have expiration time and get re-synced only if they get too old. If you do not mind using stale caches you can short-circuit this check, e.g. by adding `and False` condition here:
https://github.com/afilipovich/gglsbl/blob/master/gglsbl/client.py#L162

however it may produce false positives and negatives.

**Comment by Fujiaoji** [comment]
Sorry for the late response. I missed the message because it is blocked by my email. It is a little long time so I forget what is the question for the testing samples. I remember I run it in the linux. For the second question, it helps a lot. Thanks for your reply.
