### ISSUE TITLE
URL canonicalization failure

### ISSUE THREAD

**Issue by Stefan-Code** [afilipovich/gglsbl#7]
Opening this issue here because I think it might be relevant. Through unit tests on windows I discovered [this (minor) issue](https://github.com/Stefan-Code/gglsbl3/issues/5). A better way to handle the [numeric host to 'normal' host conversion](https://github.com/afilipovich/gglsbl/blob/b2084f65f867631f19fc628a54548513a364760f/gglsbl/protocol.py#L347) (link to your current version) would be using [a int to ip function](https://github.com/Stefan-Code/gglsbl3/blob/10d45f5d0df285a7f69bed0e993f97a6ff6a5a11/gglsbl3/protocol.py#L439) which comes from [the util package](https://github.com/Stefan-Code/gglsbl3/blob/10d45f5d0df285a7f69bed0e993f97a6ff6a5a11/gglsbl3/util/network_utils.py#L8) in my fork.

**Comment by afilipovich** [comment]
This is definitely relevant, thanks a lot.

**Comment by afilipovich** [comment]
Backported your fix, thanks.

You may want to do the same thing to hex->IP conversion at
https://github.com/Stefan-Code/gglsbl3/blob/10d45f5d0df285a7f69bed0e993f97a6ff6a5a11/gglsbl3/protocol.py#L446

with
  host = util.int_to_ip(int(host, 16))

**Comment by Stefan-Code** [comment]
Yup, will do that. Thank you :wink:

**Comment by Stefan-Code** [comment]
One more thing, I have the strong feeling that [handling this case](https://github.com/afilipovich/gglsbl/blob/0d2a7310df67135da5ddf9cc57e8e43029666efc/gglsbl/protocol.py#L355) is redundant. I can't seem to get any test coverage for it, the
```python
if not path: 
    path = '/' 
```
seems to suffice.

**Comment by afilipovich** [comment]
Cool, thanks. Trailing slash conditional is to comply with [canonicalization spec](https://developers.google.com/safe-browsing/developers_guide_v3#Canonicalization) "The URL must include a path component; that is, it must have a trailing slash". I guess I just did not add a unit test for it.

Wonder if you use any tools to check unit test coverage?

**Comment by Stefan-Code** [comment]
Well, I added 'google.com' -> 'http://google.com/' to the tests and it passes without covering the case linked above, so I think [it is handled earlier already](https://github.com/Stefan-Code/gglsbl3/blob/4631ef1e518774487e88cee47a6a4351871061ea/gglsbl3/protocol.py#L425).
For checking test coverage, I added a script [`./nose.sh`](https://github.com/Stefan-Code/gglsbl3/blob/4631ef1e518774487e88cee47a6a4351871061ea/nose.sh#L4) or `nose.bat` for windows.
[Travis also runs the nosetests with coverage](https://travis-ci.org/Stefan-Code/gglsbl3/jobs/91708117) and uploads to coveralls.

**Comment by afilipovich** [comment]
That makes sense, thanks.

**Comment by Stefan-Code** [comment]
I think this can be closed, right?

**Comment by afilipovich** [comment]
yep, sure, thx
