### ISSUE TITLE
URL permutations not covering all cases

### ISSUE THREAD

**Issue by Stefan-Code** [afilipovich/gglsbl#8]
When looking up `http://malware.testing.google.test/testing/malware` using the python implementation, it returns **NOT** blacklisted.
When performing the [same lookup on the google lookup page](https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=http://malware.testing.google.test/testing/malware) **it is listed**.
Maybe when generating the permutations, a trailing slash should be appended to urls like `http://foo.com/bar/file` because that's what google seems to do on their lookup page.
When looking up `http://malware.testing.google.test/testing/malware/` with python, you see it is blacklisted.
[Link to gglsbl3 issue](https://github.com/Stefan-Code/gglsbl3/issues/7)

**Comment by Stefan-Code** [comment]
It looks like [the developers guide](https://developers.google.com/safe-browsing/developers_guide_v3?hl=en) doesn't cover a filename without extension and the current python implementation seems to be correct. I am wondering though, why google's lookup tool handles this differently/

**Comment by afilipovich** [comment]
Good catch.

I guess diagnostic page works directly with blacklisted URLs rather than hashes, otherwise it would not be able to tell if http://malware.testing.google.test/testing is "partially dangerous".

I think the best course of actions is to report this use case to Google.

**Comment by Stefan-Code** [comment]
Yeah you're right, didn't see the "partially dangerous" happen before. I'll see if I can find a way to contact someone (but I think it might be difficult to get a response). I guess we can close this too, because implementing this change would be against the developers guide.

**Comment by afilipovich** [comment]
Yeah, I agree. Thanks.
